from typing import Any

class Connection:
    def executescript(self, script: str, /) -> None: ...
    def commit(self) -> None: ...
    def execute(self, sql: str, params: tuple[Any, ...] | None = ...) -> Any: ...
    def executemany(self, sql: str, params: list[tuple[Any, ...]], /) -> Any: ...
    def close(self) -> None: ...

def connect(path: str, /) -> Connection: ...
