name: Environment1
values:
  - key: base_url
    value: 'http://localhost:4789'
  - key: executor-token
    value: ''
  - key: current_tool_address
    value: ''
  - key: tool_path
    value: ''
  - key: integration_slug
    value: ''
  - key: connection_owner
    value: org
  - key: connection_integration
    value: ''
  - key: connection_name
    value: ''
  - key: provider_key
    value: ''
  - key: policy_id
    value: ''
  - key: execution_id
    value: ''
  - key: oauth_client_slug
    value: ''
  - key: oauth_state
    value: ''
  - key: toolkit_slug
    value: backend
  - key: toolkit_id
    value: ''
  - key: toolkit_policy_id
    value: ''
  - key: toolkit_connection_id
    value: ''
  - key: mcp_session_id
    value: ''
  - key: mcp_toolkit_session_id
    value: ''
  - key: org_slug
    value: ''
