$kind: http-example
request:
  url: "{{base_url}}/api/onepassword/config"
  method: DELETE
response:
  statusCode: 200
  statusText: OK
  headers:
    content-type: application/json
    content-length: "0"
    date: Wed, 08 Jul 2026 19:06:14 GMT
  body:
    type: text
    content: |-

order: 1783537574203
