exclude_patterns:
- '**/.*'
- '**/__pycache__'
- '**/node_modules'
- '**/target'
- '**/build/assets'
- '**/dist'
- '**/vendor/*.*/*'
- '**/vendor/*'
- '**/.cocoindex_code'
- '**/full/**'
- '**/full/*'
- 'full/**'
- 'full/*'
include_patterns:
- '**/*.json'
- '*.json'
- '**/*.md'
- '*.md'

#chunkers:
#  - ext: json              # use a custom chunker for .toml files
#    module: custom_json_chunker:json_chunker