/** TypeScript SDK for cyt-indexer (Rust-backed catalog indexing). */

export {
  CatalogIndex,
  anthropicToolToCatalogEntry,
  anthropicToolsToCatalogEntries,
  buildCatalogFromTools,
  buildCatalogIndex,
  catalogIndexToolSchemaMetadata,
  catalogToolCount,
  collectEnums,
  prepareToolEntry,
  truncateDescription,
} from "./build.js";
export {
  DecomposedCatalog,
  chunkSurvivorKey,
  loadCatalog,
  removedChunks,
  resolveBuildCatalog,
  retrieveCatalogToolCount,
  retrieveTools,
  type DecomposedCatalogDict,
  type JsonRecord,
  type PolicyContextJs,
  type PolicyOptions,
  type RemovedChunksOptions,
  type RetrieveToolsOptions,
} from "./retrieve.js";
export {
  configureRuntimeDefaults,
  defaultMcpPolicy,
  defaultSystemPolicy,
  decomposedScore,
  emptyOptionalFallbackK,
  enumScore,
  rerankScore,
  type RuntimeDefaultsConfig,
} from "./runtime-defaults.js";
export {
  builderMemoryOnly,
  catalogPrefix,
  configurePathConstants,
  defaultCatalogDir,
  decomposedPrefix,
  decomposedRoot,
  getRootToolKey,
  jsonExt,
  mdExt,
  toDecomposedKey,
  toolIdFromDecomposedRel,
  writeCatalogPrune,
} from "./paths.js";
export { CatalogBuilder, writeCatalogIndex } from "./catalog-io.js";
export {
  extractDocumentText,
  extractJsonCatalogDocument,
  extractLevelInfo,
  extractMdCatalogDocument,
} from "./documents.js";
export {
  bm25CohesionChunk,
  cohesionConfigToNative,
  defaultBm25CohesionConfig,
  type CohesionChunk,
} from "./bm25Cohesion.js";
export {
  bm25CatalogFingerprint,
  bm25FrontmatterGate,
  bm25ScoreCatalog,
  bm25SearchSkillChunks,
  batchReconstructSkillMatches,
  configureBm25Defaults,
  expSimilarity,
  greedySelectSkillItems,
  type Bm25FrontmatterGateResult,
  type Bm25ScoreCatalogOptions,
  type Bm25SearchSkillChunksResult,
} from "./bm25Search.js";
export {
  configureTokenizerDefaults,
  countJsonTokens,
  countTokens,
  countTokensBatch,
} from "./tokens.js";
export {
  configureMemoryCache,
  ensureSkillsRegistry,
  ensureToolCatalog,
  ensureToolCatalogFromEntries,
  toolsCatalogContentHash,
  type CachePolicy,
  type SkillEntryRef,
  type SkillSourceInput,
  type ToolCatalogCacheResult,
} from "./cache.js";
export {
  SkillsBuilder,
  buildSkillsIndex,
  buildPageIndexOnly,
  buildChunkVariant,
  pageIndexValid,
  chunkVariantValid,
  repairSkillChunks,
  repairSkillVariantChunks,
  loadSkillsIndexFromEntry,
  loadMergedSkillDocumentJson,
  finalizeSkillDocumentJson,
  updateSkillDocumentSourcePath,
  defaultPageIndexConfig,
  getSkillContentRetrieveResult,
  getSkillDocument,
  getSkillLineContent,
  getSkillLineContentFromSpec,
  getSkillStructure,
  loadSkillsIndexFromDir,
  mdToTree,
  pageIndexConfigFromMapping,
  pageIndexConfigFromPartial,
  pageIndexConfigToNative,
  pageIndexConfigWithoutChunking,
  parseSkillChunkIds,
  parseSkillNodeIds,
  tokenCountFromDecomposedFrontmatter,
  reconstructSkillMarkdown,
  skillsIndexFromDecomposedDir,
  writeReconstructedSkill,
  writeSkillsIndex,
  type Bm25CohesionConfig,
  type PageIndexConfig,
  type PageIndexConfigInput,
  type ReconstructOptions,
  type SkillsIndexDict,
} from "./pageindex.js";
export {
  pruneCatalogBm25AndRetrieve,
  classifyAndCountCatalog,
  searchSkillsAndSelect,
  buildSkillNodeCatalog,
  coordinateBm25Prune,
  type PruneBm25Options,
  type SearchSkillsOptions,
  type CoordinateBm25Options,
} from "./pipeline.js";

// Full policy surface (mirrors cyt_indexer.policies).
export * from "./policies.js";
