from typing import Any

class Client:
    def __init__(self, transport: Any) -> None: ...
    def __enter__(self) -> Client: ...
    def __exit__(self, *args: Any) -> None: ...
    def list_tools(self) -> list[Any]: ...
