from collections.abc import Callable, Sequence
from typing import Any

class FastMCP:
    def __init__(self, name: str, **kwargs: Any) -> None: ...
    def add_tool(self, tool: Any) -> None: ...
    def add_transform(self, transform: Any) -> None: ...
    def mount(self, server: Any, **kwargs: Any) -> None: ...
    async def list_tools(self) -> Sequence[Any]: ...
    def custom_route(
        self,
        path: str,
        *,
        methods: list[str] | None = ...,
    ) -> Callable[..., Any]: ...
    async def call_tool(
        self,
        name: str,
        arguments: dict[str, Any] | None = ...,
    ) -> Any: ...
    async def run_http_async(self, **kwargs: Any) -> None: ...
    def run(self, transport: str, **kwargs: Any) -> None: ...
