$kind: http-request
url: "{{base_url}}/api/google/integrations/{{integration_slug}}/config"
method: POST
body:
  type: json
  content: |
    {
      "authenticationTemplate": [],
      "mode": "merge"
    }
examples: .resources/04 - POST configure Google integration.resources/examples
order: 2204
