defaults:
#  system_tool_policy: prune_optional
#  mcp_tool_policy: prune_all
  is_persistent: true
  remote: 
    embedding_model_nick: embed-qwen3-8b
    reranking_model_nick: rerank-qwen3-8b
    llm_model_nick: llm-mercury-2
  inprocess: []

  reranking_enabled: true
  embedding_enabled: true
  intent_router:
    top_k: 10
    threshold: 0.28
models:
  llm:
    remote:
      - name: openai/gpt-oss-120b
        provider: openrouter
        nick: gpt-oss-120b
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 128000
        pricing:
          # match_litellm: "openrouter/openai/gpt-oss-120b"
          input_cost_per_token: 1.5e-07
          output_cost_per_token": 6e-07
        # base_url: https://openrouter.ai/api/v1
      - name: inception/mercury-2
        provider: openrouter
        nick: mercury-2
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 1280000
        pricing:
          # match_litellm: 
          input_cost_per_token: 2.5e-07
          output_cost_per_token": 7.5e-07
        # base_url: https://openrouter.ai/api/v1
      - name: google/gemini-3-flash-preview
        provider: openrouter
        nick: gemini-3-flash
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 10000000
        domain_match: ["openrouter.ai"]
        pricing:
          # match_litellm: 
          input_cost_per_token: 2.5e-07
          output_cost_per_token": 7.5e-07
        # base_url: https://openrouter.ai/api/v1
  embeddings:
    inprocess:
      - name: sentence-transformers/all-MiniLM-L6-v2
        nick: all-MiniLM-L6-v2
    remote:
      - name: qwen/qwen3-embedding-8b
        provider: openrouter
        nick: embed-qwen3-8b
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 32000
        # base_url: https://openrouter.ai/api/v1
      - name: all-minilm:33m
        provider: ollama
        nick: all-minilm
        max_tokens: 512
        # key_var_name: OPENROUTER_API_KEY
        # base_url: http://localhost:11434
      - name: nomic-embed-text:137m-v1.5-fp16
        provider: ollama
        nick: nomic-embed-text
        max_tokens: 2000
        # key_var_name: OPENROUTER_API_KEY
        # base_url: http://localhost:11434
      - name: qwen3-embedding:8b
        provider: ollama
        nick: qwen3-embedding-8b
        max_tokens: 32000
        # key_var_name: OPENROUTER_API_KEY
        # base_url: http://localhost:11434
  rerankers:
    remote:
      - name: Qwen/Qwen3-Reranker-8B
        provider: deepinfra
        nick: rerank-qwen3-8b
        key_var_name: DEEPINFRA_API_KEY
        max_tokens: 32000
        # base_url: https://api.deepinfra.com/v1
        pricing:
          input_cost_per_token: 5e-08
          # output_cost_per_token": 5e-08
          # match_litellm: "deepinfra/Qwen/Qwen3-Reranker-8B"

vectordb:
  dir: .vectordb

pruning:
  per_tool:
    mcp__hedl__hedl_convert_from: prune_optional
    Agent: prune_optional
    mcp__hedl__batch: prune_all
    mcp__fff__multi_grep: always_include

  pipeline:
#    - rerank
    - llm

network:
  proxy:
    port: 8834
    upstreams:
      - upstream: anthropic
        url: https://openrouter.ai/api
        kind: anthropic
    endpoints:
      - anthropic

stats:
  enabled: true
  store_full_tools: false
  database:
    path: ~/.configs/sca/stats.db