defaults:
  #  system_tool_policy: prune_optional
  #  mcp_tool_policy: prune_all
  is_persistent: true
  remote:
    reranking_model_nick: rerank-qwen3-8b
    llm_model_nick: mercury-2
  inprocess: []

  reranking_enabled: true
models:
  llm:
    minimum_tools: 50
    remote:
      - name: openai/gpt-oss-120b
        provider: openrouter
        nick: gpt-oss-120b
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 128000
        pricing:
          # match_litellm: "openrouter/openai/gpt-oss-120b"
          input_cost_per_token: 1.5e-07
          output_cost_per_token: 6e-07
        # base_url: https://openrouter.ai/api/v1
      - name: inception/mercury-2
        provider: openrouter
        nick: mercury-2
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 1280000
        pricing:
          # match_litellm:
          input_cost_per_token: 2.5e-07
          output_cost_per_token: 7.5e-07
        # base_url: https://openrouter.ai/api/v1
      - name: google/gemini-3-flash-preview
        provider: openrouter
        nick: gemini-3-flash
        key_var_name: OPENROUTER_API_KEY
        max_tokens: 10000000
        domain_match: ["openrouter.ai"]
        pricing:
          # match_litellm:
          input_cost_per_token: 2.5e-07
          output_cost_per_token: 7.5e-07
        # base_url: https://openrouter.ai/api/v1
  rerankers:
    minimum_tools: 29
    remote:
      - name: Qwen/Qwen3-Reranker-8B
        provider: deepinfra
        nick: rerank-qwen3-8b
        key_var_name: DEEPINFRA_API_KEY
        max_tokens: 32000
        # base_url: https://api.deepinfra.com/v1
        pricing:
          input_cost_per_token: 5e-08
          # output_cost_per_token": 5e-08
          # match_litellm: "deepinfra/Qwen/Qwen3-Reranker-8B"

pruning:
  per_tool:
    Agent: prune_optional
    mcp__hedl__hedl_convert_from: prune_optional
    mcp__hedl__batch: prune_all
    mcp__fff__multi_grep: always_include

  pipeline:
    - rerank
#    - llm

network:
  proxy:
    reverse:
      debug_log_max_body_bytes: 1048576
      http2:
        upstream: true # uv pip install h2
        serve: true # uv pip install 'hypercorn[h2]' + TLS below
        ssl: # openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout src/crt/key.pem -out src/crt/cert.pem -subj "/CN=localhost" -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"
          keyfile: src/crt/key.pem
          certfile: src/crt/cert.pem
      port: 8834
      upstreams:
        - upstream: anthropic
          url: https://openrouter.ai/api
          kind: anthropic
      endpoints:
        - anthropic

stats:
  enabled: true
  store_full_tools: false
  strong_model: gemini-3-flash # nickname from models.llm
  database:
    path: ~/.configs/cyt/stats.db
