"""Legacy DEFAULT_* constants -> defaults.yaml key paths."""

from __future__ import annotations

# Every DEFAULT_* constant removed from cyt.config.__init__.py (HEAD) must
# resolve to an existing path in defaults.yaml.
LEGACY_DEFAULT_PATHS: dict[str, tuple[str, ...]] = {
    "DEFAULT_REVERSE_PORT": ("network", "proxy", "reverse", "port"),
    "DEFAULT_PRUNING_PIPELINE": ("tools", "sequence"),
    "DEFAULT_STATS_DB_PATH": ("stats", "database", "path"),
    "DEFAULT_SYSTEM_TOOL_POLICY": ("tools", "policy", "system_tool"),
    "DEFAULT_MCP_TOOL_POLICY": ("tools", "policy", "mcp_tool"),
    "DEFAULT_DEBUG_LOG_MAX_BODY_BYTES": ("network", "proxy", "reverse", "debug_log_max_body_bytes"),
    "DEFAULT_DEBUG_LOG_DIR": ("network", "proxy", "reverse", "debug_log_dir"),
    "DEFAULT_MIN_TOOLS_PRUNING": ("tools", "policy", "minimum_tools"),
    "DEFAULT_BM25_INDEX_DIR": ("models", "bm25", "index_dir"),
    "DEFAULT_BM25_STEM_LANGUAGE": ("models", "bm25", "stem_language"),
    "DEFAULT_BM25_STOPWORDS": ("models", "bm25", "stopwords"),
    "DEFAULT_BM25_SCORE_TOOL": ("tools", "pipelines", "bm25", "score_tool"),
    "DEFAULT_BM25_PRUNE_ENUMS": ("tools", "pipelines", "bm25", "prune_enums"),
    "DEFAULT_BM25_SCORE_TOOL_ENUM": ("tools", "pipelines", "bm25", "score_tool_enum"),
    "DEFAULT_BM25_SCORE_SKILLS": ("tools", "pipelines", "bm25", "score_skills"),
    "DEFAULT_SKILLS_ENABLED": ("skills", "enabled"),
    "DEFAULT_SKILLS_PIPELINE": ("skills", "pipeline"),
    "DEFAULT_SKILLS_CATALOG_DIR": ("skills", "catalog_dir"),
    "DEFAULT_CACHE_ENABLED": ("cache", "enabled"),
    "DEFAULT_CACHE_BM25_DIR": ("cache", "bm25_dir"),
    "DEFAULT_CACHE_SKILLS_DIR": ("cache", "skills_dir"),
    "DEFAULT_CACHE_TOOLS_DIR": ("cache", "tools_dir"),
    "DEFAULT_INJECT_VIA": ("defaults", "inject_via_default"),
    "DEFAULT_INJECT_INTO_USER_MESSAGE": ("network", "proxy", "reverse", "inject_into_user_message"),
    "DEFAULT_SKILLS_FRONTMATTER_UPPER_LIMIT": ("skills", "frontmatter_upper_limit"),
    "DEFAULT_SKILLS_MAX_TOKENS_PER_REQUEST": ("skills", "max_tokens_per_request"),
    "DEFAULT_SKILLS_BM25_NODE_FALLBACK_THRESHOLD": ("skills", "bm25_node_fallback_threshold"),
    "DEFAULT_SKILLS_HOOK_REQUEST_BUDGET_FRACTION": ("skills", "hook", "request_budget_fraction"),
    "DEFAULT_SKILLS_HOOK_INJECT_CAP_MULTIPLIER": (
        "skills",
        "hook",
        "inject_cap_multiplier_of_request_tokens",
    ),
    "DEFAULT_SKILLS_HOOK_CURSOR_RULE_FILE_ENABLED": (
        "agents",
        "cursor",
        "hook",
        "cursor_rule_file",
        "enabled",
    ),
    "DEFAULT_SKILLS_HOOK_AGENT_INTERCEPTOR_ENABLED": (
        "skills",
        "hook",
        "agent_interceptor",
        "enabled",
    ),
    "DEFAULT_SKILLS_HOOK_AGENT_INTERCEPTOR_MIN_ITEMS": (
        "skills",
        "hook",
        "agent_interceptor",
        "min_items",
    ),
    "DEFAULT_SKILLS_PROXY_REQUEST_BUDGET_FRACTION": ("skills", "proxy", "request_budget_fraction"),
    "DEFAULT_SKILLS_PROXY_INJECT_CAP_FRACTION": (
        "skills",
        "proxy",
        "inject_cap_fraction_of_savings",
    ),
    "DEFAULT_SKILLS_PROXY_SAVINGS_BUDGET_FRACTION": ("skills", "proxy", "savings_budget_fraction"),
    "DEFAULT_SKILLS_PROXY_SAVINGS_RATE_THRESHOLD": ("skills", "proxy", "savings_rate_threshold"),
    "DEFAULT_TOOLS_ENABLED": ("tools", "enabled"),
    "DEFAULT_TOOLS_HOOK_TOOLS_FROM": ("tools", "hook", "tools_from"),
    "DEFAULT_TOOLS_HOOK_EXECUTOR_URL": ("tools", "hook", "executor_url"),
    "DEFAULT_TOOLS_HOOK_EXECUTOR_TOKEN_VAR": ("tools", "hook", "executor_token_var"),
    "DEFAULT_TOOLS_HOOK_CLOUDFLARE_URL": ("tools", "hook", "cloudflare_url"),
    "DEFAULT_TOOLS_HOOK_CLOUDFLARE_ACCESS_CLIENT_ID_VAR": ("tools",
        "hook",
        "cloudflare_access_client_id_var",
    ),
    "DEFAULT_TOOLS_HOOK_CLOUDFLARE_ACCESS_CLIENT_SECRET_VAR": ("tools",
        "hook",
        "cloudflare_access_client_secret_var",
    ),
    "DEFAULT_TOOLS_HOOK_MCP_DEFINITIONS_FILE": ("tools", "hook", "mcp_definitions_file"),
    "DEFAULT_CLOUDFLARE_CACHE_CATALOG_REFRESH_SECONDS": ("tools",
        "hook",
        "cloudflare_cache",
        "catalog_refresh_seconds",
    ),
    "DEFAULT_CLOUDFLARE_CACHE_SERVER_HEALTH_REFRESH_SECONDS": ("tools",
        "hook",
        "cloudflare_cache",
        "server_health_refresh_seconds",
    ),
    "DEFAULT_CLOUDFLARE_CACHE_DISK_FLUSH_SECONDS": ("tools",
        "hook",
        "cloudflare_cache",
        "disk_flush_seconds",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_ENABLED": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "enabled",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_WINDOW_SIZE": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "window_size",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_MIN_DEGRADED": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "min_degraded",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_MIN_TRANSITIONS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "min_transitions",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_BASE_QUARANTINE_SECONDS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "base_quarantine_seconds",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_PER_DEGRADED_SECONDS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "per_degraded_seconds",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_PER_TRANSITION_SECONDS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "per_transition_seconds",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_MAX_QUARANTINE_SECONDS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "max_quarantine_seconds",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_RECOVERY_HEALTHY_SAMPLES": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "recovery_healthy_samples",
    ),
    "DEFAULT_CONNECTION_HEALTH_FLAPPING_PER_EPISODE_SECONDS": ("tools",
        "hook",
        "connection_health",
        "flapping",
        "per_episode_seconds",
    ),
    "DEFAULT_EXECUTOR_CACHE_HEALTH_REFRESH_SECONDS": ("tools",
        "hook",
        "executor_cache",
        "health_refresh_seconds",
    ),
    "DEFAULT_EXECUTOR_CACHE_HEALTH_PROBE_CONCURRENCY": ("tools",
        "hook",
        "executor_cache",
        "health_probe_concurrency",
    ),
    "DEFAULT_EXECUTOR_CACHE_CATALOG_SCHEMA_REFRESH_SECONDS": ("tools",
        "hook",
        "executor_cache",
        "catalog_schema_refresh_seconds",
    ),
    "DEFAULT_EXECUTOR_CACHE_DISK_FLUSH_SECONDS": ("tools",
        "hook",
        "executor_cache",
        "disk_flush_seconds",
    ),
    "DEFAULT_MCPC_EXECUTABLE": ("tools", "hook", "mcpc", "executable"),
    "DEFAULT_MCPC_CACHE_SESSION_REFRESH_SECONDS": ("tools",
        "hook",
        "mcpc",
        "cache",
        "session_refresh_seconds",
    ),
    "DEFAULT_MCPC_CACHE_TOOLS_REFRESH_SECONDS": ("tools",
        "hook",
        "mcpc",
        "cache",
        "tools_refresh_seconds",
    ),
    "DEFAULT_MCPC_CACHE_SKILLS_REFRESH_SECONDS": ("tools",
        "hook",
        "mcpc",
        "cache",
        "skills_refresh_seconds",
    ),
    "DEFAULT_MCPC_CACHE_DISK_FLUSH_SECONDS": ("tools",
        "hook",
        "mcpc",
        "cache",
        "disk_flush_seconds",
    ),
    "DEFAULT_MCPC_SKILLS_OWN_ENABLED": ("tools",
        "hook",
        "mcpc",
        "skills",
        "own",
        "enabled",
    ),
    "DEFAULT_MCPC_SKILLS_IN_SESSION_ENABLED": ("tools",
        "hook",
        "mcpc",
        "skills",
        "in_session",
        "enabled",
    ),
    "DEFAULT_MCPC_RESOURCES_ENABLED": ("tools", "hook", "mcpc", "resources", "enabled"),
    "DEFAULT_MCPC_RESOURCES_MIME_TYPES": ("tools",
        "hook",
        "mcpc",
        "resources",
        "mimeType",
    ),
    "DEFAULT_CYT_MCP_EXECUTABLE": ("tools", "hook", "cyt_mcp", "executable"),
    "DEFAULT_CYT_MCP_AGENT": ("defaults", "cyt_mcp_agent"),
    "DEFAULT_CYT_MCP_CACHE_TOOLS_REFRESH_SECONDS": ("tools",
        "hook",
        "cyt_mcp",
        "cache",
        "tools_refresh_seconds",
    ),
    "DEFAULT_CYT_MCP_CACHE_DISK_FLUSH_SECONDS": ("tools",
        "hook",
        "cyt_mcp",
        "cache",
        "disk_flush_seconds",
    ),
    "DEFAULT_SELECTOR_SOFT_BUDGET_TOOLS_TOTAL": ("tools", "selector_soft_budget"),
    "DEFAULT_SELECTOR_SOFT_BUDGET_SKILLS_TOTAL": ("skills", "selector_soft_budget"),
    "DEFAULT_SELECTOR_BULK_MAX_TOKENS": ("tools", "selector_bulk_max_tokens"),
    "DEFAULT_MAX_PRUNE_BATCH_WORKERS": ("tools", "max_batch_workers"),
}

INJECT_VIA_AGENTS: tuple[str, ...] = ("cursor", "claude", "codex")
